---
- name: execute tasks on the undercloud
  include_tasks: break_undercloud.yml
  when: inventory_hostname.startswith('undercloud')

- name: execute tasks on compute node 0
  include_tasks: break_compute-0.yml
  when: inventory_hostname == groups['Compute'][0]
