---
- name: make sure this is OSP 17
  shell: grep -q "Red Hat OpenStack Platform release 17\." /etc/rhosp-release
  when: inventory_hostname.startswith('undercloud')

- name: execute tasks on the undercloud
  include_tasks: break_undercloud.yml

- name: execute tasks on compute node 0
  include_tasks: break_compute-0.yml
  when: inventory_hostname == groups['Compute'][0]
