---
- name: Download things
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - "{{ ovn_package }}"
    - "{{ ovn_host_package }}"

- name: Copy things
  become: yes
  shell: "podman cp /tmp/{{ item }} ovn_controller:/tmp/."
  with_items:
    - "{{ ovn_package }}"
    - "{{ ovn_host_package }}"

- name: Install things
  become: yes
  shell: |
    ovs-vsctl remove open . external_ids ovn-match-northd-version
    podman exec ovn_controller rpm -Uvh --oldpackage /tmp/{{ ovn_package }} /tmp/{{ ovn_host_package }}

- name: Restart things
  become: yes
  systemd:
    state: restarted
    name: tripleo_ovn_controller
