---
- name: Load Podified variables
  ansible.builtin.include_vars: podified.yml
  tags: always

- name: start environment
  ansible.builtin.include_tasks:
    file: start.yml
    apply:
      tags: start
      delegate_to: 127.0.0.1
      run_once: true
  tags: start

- name: grade environment
  ansible.builtin.include_tasks:
    file: grade.yml
    apply:
      tags: grade
      delegate_to: 127.0.0.1
      run_once: true
  tags: grade

- name: fix environment - run neutron_api tasks
  ansible.builtin.include_tasks:
    file: fix_controller.yml
    apply:
      tags: fix
      delegate_to: 127.0.0.1
      run_once: true
  tags: fix

- name: fix environment
  ansible.builtin.include_tasks:
    file: fix_undercloud.yml
    apply:
      tags: fix
      delegate_to: 127.0.0.1
      run_once: true
  tags: fix

- name: finish environment
  ansible.builtin.include_tasks:
    file: finish.yml
    apply:
      tags: finish
      delegate_to: 127.0.0.1
      run_once: true
  tags: finish
