---
- name: Load Tripleo variables
  ansible.builtin.include_vars: tripleo.yml
  when: installer == 'tripleo'
  tags: always

- name: start environment - run undercloud tasks
  ansible.builtin.include_tasks:
    file: start.yml
    apply:
      tags: start
  when: inventory_hostname.startswith('undercloud')
  tags: start

- name: grade environment - run undercloud tasks
  ansible.builtin.include_tasks:
    file: grade.yml
    apply:
      tags: grade
  when: inventory_hostname.startswith('undercloud')
  tags: grade

- name: fix environment - run neutron_api tasks
  ansible.builtin.include_tasks:
    file: fix_controller.yml
    apply:
      tags: fix
  when: inventory_hostname == groups['Controller'][0]
  tags: fix

- name: fix environment - run undercloud tasks
  ansible.builtin.include_tasks:
    file: fix_undercloud.yml
    apply:
      tags: fix
  when: inventory_hostname.startswith('undercloud')
  tags: fix

- name: finish environment - run undercloud tasks
  ansible.builtin.include_tasks:
    file: finish.yml
    apply:
      tags: finish
  when: inventory_hostname.startswith('undercloud')
  tags: finish
