---
- name: "delete OpenStack resources for scenario {{ scenario }}"
  shell: |
    {{ osp_get_credentials_cmd }}

    port_id=$({{ oc_cmd }} openstack port list --server scenario-{{ scenario }}-vm -c ID -f value)
    {{ oc_cmd }} openstack floating ip list --port $port_id -c ID -f value | xargs {{ oc_cmd }} openstack floating ip delete

    {{ oc_cmd }} openstack server delete scenario-{{ scenario }}-vm

    {{ oc_cmd }} openstack keypair delete scenario-{{ scenario }}-key

    {{ oc_cmd }} openstack router remove subnet scenario-{{ scenario }}-router scenario-{{ scenario }}-subnet
    {{ oc_cmd }} openstack router delete scenario-{{ scenario }}-router

    {{ oc_cmd }} openstack security group delete scenario-{{ scenario }}-sg

    for net in $({{ oc_cmd }} openstack network list | grep scenario-{{ scenario }}-network | awk '{ print $2 }'); do
      {{ oc_cmd }} openstack network delete $net
    done

- name: "delete scenario {{ scenario }} working directory"
  ansible.builtin.file:
    path: "{{ working_dir }}/.scenario{{ scenario }}"
    state: absent
