---
- name: fix the scenario {{ scenario }}
  shell: |
    {{ osp_get_credentials_cmd }}

    {{oc_cmd }} openstack security group rule create --ingress --protocol tcp --dst-port 22 scenario-{{ scenario }}-sg
