---
- name: Set oc command
  ansible.builtin.set_fact:
    oc_cmd: ""
  tags: always

- name: Get credentials command
  ansible.builtin.set_fact:
    osp_get_credentials_cmd: "source {{ overcloudrc_file }}"
  tags: always

- name: break environment - run undercloud tasks
  ansible.builtin.include_tasks:
    file: break.yml
    apply:
      tags: break
  when: inventory_hostname.startswith('undercloud')
  tags: break

- name: grade environment - run undercloud tasks
  ansible.builtin.include_tasks:
    file: grade.yml
    apply:
      tags: grade
  when: inventory_hostname.startswith('undercloud')
  tags: grade

- name: fix environment - run undercloud tasks
  ansible.builtin.include_tasks:
    file: fix.yml
    apply:
      tags: fix
  when: inventory_hostname.startswith('undercloud')
  tags: fix

- name: cleanup environment - run undercloud tasks
  ansible.builtin.include_tasks:
    file: cleanup.yml
    apply:
      tags: cleanup
  when: inventory_hostname.startswith('undercloud')
  tags: cleanup
