---
- name: "{{ snapshot_action }} virtual environment using {{ backup_name }} backup name"
  shell: "{{ working_dir }}/{{ downloads_dir }}/{{ simple_snapshot_exec }} {{ snapshot_action }} {{ backup_name }} >> {{ working_dir }}/{{ downloads_dir }}/snapshot.log"
  become: yes
  register: output
  failed_when: '"Domain snapshot not found" in output.stderr'
