---
- name: fix the scenario {{ scenario }}
  ansible.builtin.shell: |
    {{ osp_get_credentials_cmd }}

    source {{ temp_results_file }}

    for pf in $({{ oc_osp_cmd }} openstack floating ip port forwarding list $pf_fip_id -c ID -f value); do
      {{ oc_osp_cmd }} openstack floating ip port forwarding delete $pf_fip_id $pf
    done

    {{ oc_osp_cmd }} openstack server delete scenario-{{ scenario }}-fip-vm
    {{ oc_osp_cmd }} openstack server delete scenario-{{ scenario }}-pf-vm

    {{ oc_osp_cmd }} openstack router remove subnet scenario-{{ scenario }}-router scenario-{{ scenario }}-subnet

    for net in $({{ oc_osp_cmd }} openstack network list | grep scenario-{{ scenario }}-network | awk '{ print $2 }'); do
      {{ oc_osp_cmd }} openstack network delete $net
    done

    {{ oc_osp_cmd }} openstack network create --provider-network-type geneve scenario-{{ scenario }}-network
    {{ oc_osp_cmd }} openstack subnet create --network scenario-{{ scenario }}-network --subnet-range 192.168.1{{ scenario }}.0/24 scenario-{{ scenario }}-subnet
    {{ oc_osp_cmd }} openstack router add subnet scenario-{{ scenario }}-router scenario-{{ scenario }}-subnet

    {{ oc_osp_cmd }} openstack server create --flavor m1.small --image {{ image_name }} --nic net-id=scenario-{{ scenario }}-network --key-name scenario-{{ scenario }}-key --security-group scenario-{{ scenario }}-sg scenario-{{ scenario }}-fip-vm --wait
    {{ oc_osp_cmd }} openstack server show scenario-{{ scenario }}-fip-vm | grep -q "status.*ACTIVE"

    port_id=$({{ oc_osp_cmd }} openstack port list --server scenario-{{ scenario }}-fip-vm -c ID -f value | head)
    {{ oc_osp_cmd }} openstack floating ip set --port $port_id $fip_id

    {{ oc_osp_cmd }} openstack server create --flavor m1.small --image {{ image_name }} --nic net-id=scenario-{{ scenario }}-network --key-name scenario-{{ scenario }}-key --security-group scenario-{{ scenario }}-sg scenario-{{ scenario }}-pf-vm --wait
    {{ oc_osp_cmd }} openstack server show scenario-{{ scenario }}-fip-vm | grep -q "status.*ACTIVE"
    pf_port_id=$({{ oc_osp_cmd }} openstack port list --server scenario-{{ scenario }}-pf-vm -c ID -f value | head)
    pf_port_ip_address=$({{ oc_osp_cmd }} openstack port show $pf_port_id -f json | jq -r '.fixed_ips[0].ip_address')
    {{ oc_osp_cmd }} openstack floating ip port forwarding create --internal-ip-address $pf_port_ip_address --port $pf_port_id --internal-protocol-port 22 --external-protocol-port {{ pf_tcp_port }} --protocol tcp $pf_fip_id
