- name: "delete OpenStack resources for scenario {{ scenario }}"
  shell: |
    source {{ overcloudrc_file }}

    port_id=$(openstack port list --server scenario-{{ scenario }}-vm -c ID -f value)
    fips=$(openstack floating ip list --port $port_id -c ID -f value)

    openstack server delete scenario-{{ scenario }}-vm

    echo $fips | xargs openstack floating ip delete
    openstack keypair delete scenario-{{ scenario }}-key

    openstack router remove subnet scenario-{{ scenario }}-router scenario-{{ scenario }}-subnet
    openstack router delete scenario-{{ scenario }}-router

    openstack security group delete scenario-{{ scenario }}-sg

    openstack image delete scenario-{{ scenario }}-image

    openstack network delete scenario-{{ scenario }}-network

- name: "delete scenario {{ scenario }} working directory"
  ansible.builtin.file:
    path: "{{ working_dir }}/.scenario{{ scenario }}"
    state: absent
