---
- name: Load Tripleo variables
  ansible.builtin.include_vars: tripleo.yml
  when: installer == 'tripleo'
  tags: always

- name: Load Podified variables
  ansible.builtin.include_vars: podified.yml
  when: installer == 'podified'
  tags: always

- name: break environment
  ansible.builtin.include_tasks:
    file: break.yml
    apply:
      tags: break
  tags: break

- name: grade Tripleo environment
  ansible.builtin.include_tasks:
    file: grade.yml
    apply:
      tags: grade
  when: installer == 'tripleo' and inventory_hostname.startswith('undercloud')
  tags: grade

- name: grade Podified environment
  ansible.builtin.include_tasks:
    file: grade.yml
    apply:
      tags: grade
      delegate_to: '127.0.0.1'
  when: installer == 'podified'
  tags: grade

- name: fix environment
  ansible.builtin.include_tasks:
    file: fix.yml
    apply:
      tags: fix
  when: (installer == 'tripleo' and inventory_hostname in groups["Compute"]) or installer == 'podified'
  tags: fix

- name: cleanup Tripleo environment
  ansible.builtin.include_tasks:
    file: cleanup.yml
    apply:
      tags: cleanup
  when: installer == 'tripleo' and inventory_hostname.startswith('undercloud')
  tags: cleanup

- name: cleanup Podified environment
  ansible.builtin.include_tasks:
    file: cleanup.yml
    apply:
      tags: cleanup
      delegate_to: '127.0.0.1'
  when: installer == 'podified'
  tags: cleanup