---

- name: Run some things
  shell: |
    router_uuid=$(podman exec ovn_cluster_north_db_server ovn-nbctl --no-leader find logical_router 'external_ids:"neutron:router_name"="scenario-{{ scenario }}-router"' | awk '/_uuid/{ print $ 3}')
    podman exec ovn_cluster_north_db_server ovn-nbctl --no-leader lr-nat-add $router_uuid dnat_and_snat {{ hostvars['undercloud']['floating_ip']['stdout_lines'][-1] }} 192.168.1{{ scenario }}0.4
  become: yes
