---
- name: break environment - run tasks
  ansible.builtin.include_tasks:
    file: break.yml
    apply:
      tags: break
  tags: break

- name: grade environment - run undercloud tasks
  ansible.builtin.include_tasks:
    file: grade.yml
    apply:
      tags: grade
  when: inventory_hostname.startswith('undercloud')
  tags: grade

- name: fix environment - run undercloud tasks
  ansible.builtin.include_tasks:
    file: fix.yml
    apply:
      tags: fix
  tags: fix

- name: cleanup environment - run undercloud tasks
  ansible.builtin.include_tasks:
    file: cleanup.yml
    apply:
      tags: cleanup
  when: inventory_hostname.startswith('undercloud')
  tags: cleanup
