---
- name: Load Tripleo variables
  ansible.builtin.include_vars: tripleo.yml
  when: installer == 'tripleo'
  tags: always

- name: Load Podified variables
  ansible.builtin.include_vars: podified.yml
  when: installer == 'podified'
  tags: always

- name: Run scenario on the Tripleo environment
  ansible.builtin.include_tasks: scenario.yml
  when: installer == 'tripleo'
  args:
    apply:
      when: inventory_hostname.startswith('undercloud')
  tags: always

- name: Run scenario on the Podifies environment
  ansible.builtin.include_tasks: scenario.yml
  when: installer == 'podified'
  args:
    apply:
      delegate_to: 127.0.0.1
  tags: always
