- name: "delete OpenStack resources for scenario {{ scenario }}"
  shell: |
    source {{ overcloudrc_file }}

    openstack server delete scenario-{{ scenario }}-vm

    openstack keypair delete scenario-{{ scenario }}-key

    openstack security group delete scenario-{{ scenario }}-sg

- name: "delete scenario {{ scenario }} working directory"
  ansible.builtin.file:
    path: "{{ working_dir }}/.scenario{{ scenario }}"
    state: absent
