---
- name: break environment
  ansible.builtin.include_tasks:
    file: break.yml
    apply:
      tags: break
  tags: break

- name: grade environment
  ansible.builtin.include_tasks:
    file: grade.yml
    apply:
      tags: grade
  tags: grade

- name: fix environment
  ansible.builtin.include_tasks:
    file: fix.yml
    apply:
      tags: fix
  tags: fix

- name: cleanup environment
  ansible.builtin.include_tasks:
    file: cleanup.yml
    apply:
      tags: cleanup
  tags: cleanup
