---
- name: Set util command
  when: installer == "podified"
  block:
  - name: Get neutron api POD name
    ansible.builtin.shell: "{{ oc_bin }} -n {{ oc_namespace }} get pods -l service=neutron -o name | head -n 1"
    register: neutron_pod

  - name: Set command
    ansible.builtin.set_fact:
      # NOTE(slaweq): two dashes at the end are here just to add them to the final command
      # because when executing command with 'oc exec' all arguments which should be passed to the
      # final command run in the pod needs to be separated like that.
      util_cmd: "{{ container_run_cmd }} {{ neutron_pod.stdout }} --"

- name: Set util command
  ansible.builtin.set_fact:
    util_cmd: "{{ container_run_cmd }} neutron_api"
  when: installer == "tripleo"

- name: fix the scenario {{ scenario }}
  become: "{{ 'yes' if installer == 'tripleo' else 'no' }}"
  shell: "{{ util_cmd }} neutron-ovn-db-sync-util --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini --ovn-neutron_sync_mode repair"
