---
- name: Run undercloud tasks
  ansible.builtin.include_tasks: undercloud.yml
  when: ansible_hostname == "undercloud-0"

- name: Run overcloud tasks
  ansible.builtin.include_tasks: controller-0.yml
  when: ansible_hostname == "controller-0"
