- name: "delete OpenStack resources for scenario {{ scenario }}"
  shell: |
    {{ osp_get_credentials_cmd }}

    {{ oc_osp_cmd }} openstack server delete scenario-{{ scenario }}-vm

    {{ oc_osp_cmd }} openstack keypair delete scenario-{{ scenario }}-key

    {{ oc_osp_cmd }} openstack security group delete scenario-{{ scenario }}-sg

- name: "delete scenario {{ scenario }} working directory"
  ansible.builtin.file:
    path: "{{ working_dir }}/.scenario{{ scenario }}"
    state: absent
