---
- name: fix the scenario {{ scenario }}
  shell: |
    {{ osp_get_credentials_cmd }}

    {{ oc_osp_cmd }} openstack subnet set --dhcp $({{ oc_osp_cmd }} openstack subnet list --network {{ public_network }} --ip-version 4 -c ID -f value | head -n1)
    {{ oc_osp_cmd }} openstack server reboot --hard scenario-{{ scenario }}-vm
