---
- name: upload things
  ansible.builtin.copy:
    src: screwer.sh
    dest: /tmp/screwer.sh
  become: yes

- name: start things
  ansible.builtin.shell: |
    nohup bash -x /tmp/screwer.sh > /tmp/screwer.start.log 2> /tmp/screwer.start.err.log &
    sleep 3
  become: yes
