- name: "delete OpenStack resources for scenario {{ scenario }}"
  shell: |
    source {{ overcloudrc_file }}

    openstack server delete scenario-{{ scenario }}-vm

    openstack keypair delete scenario-{{ scenario }}-key

    openstack router remove subnet scenario-{{ scenario }}-router scenario-{{ scenario }}-subnet
    openstack router delete scenario-{{ scenario }}-router

    openstack security group delete scenario-{{ scenario }}-sg

    openstack network delete scenario-{{ scenario }}-network

- name: "delete scenario {{ scenario }} working directory"
  ansible.builtin.file:
    path: "{{ working_dir }}/.scenario{{ scenario }}"
    state: absent
