---
- name: Upload crudini to the hosts
  ansible.builtin.copy:
    src: "{{ crudini_rpm }}"
    dest: "/tmp/{{ crudini_rpm }}"
  become: yes

- name: install crudini
  ansible.builtin.shell: rpm -q crudini || rpm -Uvh /tmp/{{ crudini_rpm }}
  become: yes

- name: set qemu virt_type
  ansible.builtin.shell: crudini --set /var/lib/config-data/puppet-generated/nova_libvirt/etc/nova/nova.conf libvirt virt_type qemu
  become: yes

- name: restart nova compute
  ansible.builtin.systemd:
    state: restarted
    name: tripleo_nova_compute.service
  become: yes
