---
- name: Load Tripleo variables
  ansible.builtin.include_vars: tripleo.yaml
  when: installer == 'tripleo'

- name: Load Podified variables
  ansible.builtin.include_vars: podified.yaml
  when: installer == 'podified'

- name: Upload crudini to the hosts
  ansible.builtin.copy:
    src: "{{ crudini_rpm }}"
    dest: "/tmp/{{ crudini_rpm }}"
  become: yes

- name: install crudini
  ansible.builtin.shell: rpm -q crudini || rpm -Uvh /tmp/{{ crudini_rpm }}
  become: yes

- name: get qemu virt_type
  ansible.builtin.shell: "crudini --get {{ nova_config_path }} libvirt virt_type"
  become: yes
  register: virt_type_check
  ignore_errors: true

- set_fact:
    virt_type="{{ virt_type_check.stdout }}"
  when: virt_type_check is success

- set_fact:
    virt_type="kvm"
  when: virt_type_check is failed

- name: set qemu virt_type
  ansible.builtin.shell: "crudini --set {{ nova_config_path }} libvirt virt_type qemu"
  become: yes
  when: virt_type != "qemu"

- name: restart nova compute
  ansible.builtin.systemd:
    state: restarted
    name: "{{ nova_compute_service_name }}"
  become: yes
  when: virt_type != "qemu"
